### ISSUE TITLE
全サイトコンテンツ再現

### ISSUE THREAD

**Issue by elzup** [cpslab/cpslab.github.io#1]
- [ ] Top
  - [x] 研究内容
  - [ ] 講義へのリンク
  - [ ] News 窓?

~~- [ ] Research~~
  ~~- [ ] 各年度 Papers, Awards, Topics~~

- [x] 4Student
- [ ] Gallery(Works, Products)
- [ ] Members
- [x] Downloads
- [x] Contact

分離
* Classes
  * 講義資料

**Comment by nshiba** [comment]
wiki:
  - classes
  - research
