### ISSUE TITLE
画像一覧 & 画像アップロード先

### ISSUE THREAD

**Issue by nshiba** [cpslab/cpslab.github.io#3]
phots と galleryというページがあってほぼおなじコンテンツなので統一したい
というか現状LINEやらFacebookやらに適当に写真を上げているだけなので、アップロード先を固定してもらう。
そしたら、そこにある画像一覧を表示するページを作ればよさそう。
というか便利そうなので作りたい

**Comment by elzup** [comment]
![my-facebook-icoin](https://cloud.githubusercontent.com/assets/2284908/25040685/df95d54c-2145-11e7-8c85-5a72998551a5.jpg)

**Comment by cpsyokota** [comment]
![yokota](https://cloud.githubusercontent.com/assets/18566604/25516096/6fc27318-2c23-11e7-8990-6d9e445a4b20.png)

**Comment by RoneLoreto** [comment]
内容が古いため一旦〆
