### ISSUE TITLE
画像の取扱

### ISSUE THREAD

**Issue by nshiba** [cpslab/cpslab.github.io#4]
そのままgithubのリポジトリにあげていくのはまずいの(主に_posts)どっかに画像を置かないといけない

とりあえず今のiwi研サーバーでいいか

**Comment by nshiba** [comment]
とりあえずgoogle driveで

**Comment by nshiba** [comment]
> aaa

**Comment by nshiba** [comment]
google driveは直リン無理だった

**Comment by nshiba** [comment]
というか現状のiwi研サーバの画像をリンクしてるがロードが遅い気がする

**Comment by RoneLoreto** [comment]
内容が古いため一旦〆
